yl_IM:
  netty:
    server:
      port: 9081
      name: yl-im-netty
spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true # 启用自动注册
  application:
    name: yl-im-service
server:
  port: 8081
