yl_IM:
  netty:
    server:
      port: 9001
spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: false # 只用代码注册
server:
  port: 8081
